# Generated by Django 6.0.2 on 2026-02-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MangoVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("A", "MALDA"),
                            ("B", "DASHERI"),
                            ("C", "GULABKHAS"),
                            ("D", "BIJU"),
                            ("E", "ALPHANSO"),
                        ],
                        max_length=2,
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="mango_images")),
            ],
        ),
    ]
