# Generated by Django 6.0.2 on 2026-02-16 05:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mango", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mangovariety",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
